export const BARRIOS_TULUA = [
  "350 Años",
  "Aguaclara",
  "Alameda I",
  "Alameda II",
  "Alfonso López",
  "Altaflor",
  "Altos de Santa Bárbara",
  "Alvernia",
  "Americana de Vivienda (Diablos Rojos II)",
  "Antonio Nariño",
  "Asociación de Vivienda Los Pinos",
  "Asoagrin la Santa Cruz",
  "Asogrin Farfan",
  "Avenida Cali",
  "Barragán",
  "Bello Horizonte",
  "Bocas de Tuluá",
  "Bolívar",
  "Bosques de Alcalá",
  "Bosques de Marandua",
  "Bosques de Maracaibo",
  "Brisas del Cauca",
  "Buenos Aires",
  "Campoalegre",
  "Casa Huertas",
  "Centro",
  "Chicoral",
  "Chiminangos",
  "Cienegueta",
  "Ciudad Campestre",
  "Ciudadela del Sur",
  "Comfamiliar",
  "Conjunto Residencial Lusitania",
  "Céspedes",
  "Departamental",
  "Diablos Rojos I",
  "Doce de Octubre",
  "El Bosque",
  "El Bosquecito",
  "El Cóndor",
  "El Cóndor II",
  "El Descanso",
  "El Dorado",
  "El Jardín",
  "El Jazmín",
  "El Lago",
  "El Laguito",
  "El Limonar",
  "El Palmar",
  "El Picacho",
  "El Pinar",
  "El Prado",
  "El Príncipe",
  "El Recreo",
  "El Refugio",
  "El Retiro",
  "El Vergel",
  "El centro",
  "Entre Ríos",
  "Escobar",
  "Estambul",
  "Farfán",
  "Flor de la Campana",
  "Franciscanos",
  "Fátima",
  "Gaitán",
  "Guayacanes",
  "Horizonte Santa Isabel",
  "Internacional",
  "Jorge Eliecer Gaitán",
  "José Antonio Galán",
  "Juan XXIII",
  "Juan de Lemus y Aguirre",
  "La Bastilla",
  "La Caballera",
  "La Campiña",
  "La Castellana",
  "La Ceiba",
  "La Diadema",
  "La Esperanza",
  "La Estrella",
  "La Graciela",
  "La Gran Vía",
  "La Herradura",
  "La Iberia",
  "La Independencia",
  "La Inmaculada",
  "La Isla",
  "La Marina",
  "La María",
  "La Merced",
  "La Moralia",
  "La Palmera",
  "La Paz",
  "La Quinta",
  "La Rivera",
  "La Trinidad",
  "La Villa",
  "Laguito",
  "Las Acacias",
  "Las Américas",
  "Las Veraneras",
  "Brisas de San Antonio",
  "Las Colinas",
  "Las Delicias",
  "Las Ferias",
  "Las Nieves",
  "Las Olas",
  "Laureles I y II",
  "Lomitas",
  "Los Alpes",
  "Los Arrayanes",
  "Los Caimos",
  "Los Cedros",
  "Los Comuneros del corazón del Valle",
  "Los Cámbulos",
  "Los Naranjos",
  "Los Olmos",
  "Los Robles",
  "Los Tolúes",
  "Lusitania",
  "Maracaibo",
  "Marandua",
  "Miraflores",
  "Modelia",
  "Monteloro",
  "Morales",
  "Moralito",
  "Municipal",
  "Nariño",
  "Nuevo Alvernia",
  "Nuevo Farfán",
  "Nuevo Morales",
  "Obrero",
  "Palermo",
  "Palobonito Tomas Uribe",
  "Palomestizo",
  "Panamericano",
  "Paraíso",
  "Paso del Comercio",
  "Pasoancho",
  "Piedritas",
  "Playas",
  "Popular",
  "Portales del Río",
  "Porvenir",
  "Prado Norte",
  "Prados del Norte",
  "Primero de Mayo",
  "Principito",
  "Progresar",
  "Pueblo Nuevo",
  "Puerto Frazadas",
  "Quebradagrande",
  "Quintas de San Felipe",
  "Rafael Uribe Uribe",
  "Rojas",
  "Rubén Cruz Vélez",
  "Río Paila",
  "Sajonia",
  "Salesiano",
  "Samán del Norte",
  "San Antonio",
  "San Benito La Rivera",
  "San Carlos",
  "San Fernando Nuevo",
  "San Fernando Viejo",
  "San Isidro",
  "San Judas Tadeo",
  "San Lorenzo",
  "San Lucas",
  "San Luis",
  "San Marino",
  "San Martín",
  "San Pedro",
  "San Pedro Claver",
  "San Rafael",
  "San Vicente",
  "San Vicente de Paúl",
  "Santa Ana",
  "Santa Bárbara",
  "Santa Fe",
  "Santa Helena",
  "Santa Inés de Comfamiliar",
  "Santa Lucía",
  "Santa Mónica",
  "Santa Rita del Río",
  "Santa Rosa",
  "Santo Tomás",
  "Siete de Agosto",
  "Sintra SanCarlos",
  "Sucre",
  "Tenerife",
  "Tercer Milenio",
  "Tierradentro",
  "Tochecito",
  "Tres Esquinas",
  "Urbanización Peñaranda",
  "Venus",
  "Victoria",
  "Villa Argelia",
  "Villa Campestre",
  "Villa Colombia",
  "Villa Liliana",
  "Villa Mercedes",
  "Villa Nelly",
  "Villa Sandra",
  "Villa Sofía",
  "Villa del Río",
  "Villa del Sur",
  "Villanueva",
  "Villapaz",
  "Villas de San Antonio",
  "Villas de la Colina"
];

export const BARRIOS_BUGA = [
  "Los Girasoles",
  "Bello Horizonte",
  "Valle Real",
  "Albores de Sanjuanito",
  "Alto Bonito",
  "Aures",
  "El Albergue",
  "El Carmelo",
  "El Divino Niño",
  "El Jardín",
  "El Molino",
  "Estambul",
  "Fuenmayor",
  "Jorge Eliecer Gaitán",
  "José María Cabal",
  "La Concordia",
  "La Esperanza",
  "La Honda",
  "La Merced",
  "La Revolución",
  "La Ventura",
  "Los Ángeles",
  "María Luisa de la Espada",
  "Palo Blanco",
  "Ricaurte",
  "San Antonio",
  "San Marino",
  "Santa Bárbara",
  "Sucre",
  "Prados del Sur",
  "Santa Rita",
  "Prados de la Julia",
  "San Vicente",
  "San José de Las Palmas",
  "Las Palmitas",
  "Altos de Guadalupe",
  "La Catalina",
  "Portales del Río",
  "Urbanización Julia",
  "La Habana",
  "La María",
  "Monterrey",
  "El Placer",
  "Frisoles",
  "La Mesa",
  "El Rosario",
  "Playa del Buey",
  "El Salado",
  "Crucero de Nogales",
  "Miraflores",
  "Los Bancos",
  "Chambimbal",
  "El Vínculo",
  "Pueblo Nuevo",
  "Quebradaseca",
  "Zanjón Hondo",
  "El Porvenir",
  "Alaska",
  "El Manantial",
  "La Campiña",
  "La Granjita",
  "La Magdalena",
  "La Palomera",
  "Puerto Bertín",
  "El Bosque",
  "La Unidad",
  "San Antonio (Rural)",
  "Santa Bárbara (Rural)",
  "Parque Natural Las Hermosas"
];
