export const BARRIOS_TULUA = [
  "Alameda",
  "Asoagrin",
  "Buenos Aires",
  "Bolivar",
  "Brisas del bosque",
  "Brisas del Valle",
  "Bella Vista",
  "Centro",
  "Cespedes",
  "Ciudad Campestre",
  "El Bosque",
  "El Jardín",
  "El Jazmín",
  "Prados Del Norte",
  "El Recreo",
  "El Vergel",
  "Jorge Eliecer Gaitán",
  "Guayacanes",
  "La Campiña",
  "La Esperanza",
  "La Isla",
  "La María",
  "Las Américas",
  "Brisas de San Antonio",
  "Las Colinas",
  "Los Alpes",
  "Los Cedros",
  "Los Robles",
  "Maracaibo",
  "Miraflores",
  "Nariño",
  "Paraíso",
  "Paso del Comercio",
  "Pasoancho",
  "Prado Norte",
  "Progresar",
  "Pueblo Nuevo",
  "Rafael Uribe Uribe",
  "San Antonio",
  "San Fernando Nuevo",
  "San Fernando Viejo",
  "San Isidro",
  "San Judas Tadeo",
  "San Lucas",
  "San Martín",
  "San Pedro",
  "San Vicente",
  "Santa Ana",
  "Santa Bárbara",
  "Santa Fe",
  "Santa Helena",
  "Santa Mónica",
  "Santa Rosa",
  "Santa Isabel",
  "Villa del Sur",
  "Villa Liliana",
  "Villa Mercedes",
  "Villa Nelly",
  "La Paz",
  "Villas de la Colina",
  "Villas de San Antonio"
];
