export const BARRIOS_TULUA = [
  "Alfonso López",
  "Altos de Santa Bárbara",
  "Antonio Nariño",
  "Brisas del Cauca",
  "Buenos Aires",
  "Centro",
  "Chicoral",
  "Ciudadela del Sur",
  "El Bosque",
  "El Bosquecito",
  "El Cóndor",
  "El Cóndor II",
  "El Descanso",
  "El Dorado",
  "El Jardín",
  "El Jazmín",
  "El Prado",
  "El Recreo",
  "El Refugio",
  "El Retiro",
  "El Vergel",
  "Gaitán",
  "Guayacanes",
  "Horizonte Santa Isabel",
  "Internacional",
  "Jorge Eliecer Gaitán",
  "José Antonio Galán",
  "Juan XXIII",
  "Juan de Lemus y Aguirre",
  "La Bastilla",
  "La Caballera",
  "La Campiña",
  "La Castellana",
  "La Estrella",
  "La Esperanza",
  "La Gran Vía",
  "La Isla",
  "La Marina",
  "La María",
  "La Merced",
  "La Moralia",
  "La Palmera",
  "La Quinta",
  "La Rivera",
  "La Trinidad",
  "La Villa",
  "Laguito",
  "Las Acacias",
  "Las Américas",
  "Brisas de San Antonio",
  "Las Colinas",
  "Las Ferias",
  "Los Alpes",
  "Los Arrayanes",
  "Los Cedros",
  "Los Cámbulos",
  "Los Naranjos",
  "Los Robles",
  "Los Tolúes",
  "Lusitania",
  "Maracaibo",
  "Marandua",
  "Miraflores",
  "Modelia",
  "Nariño",
  "Obrero",
  "Palermo",
  "Paraíso",
  "Paso del Comercio",
  "Pasoancho",
  "Piedritas",
  "Playas",
  "Popular",
  "Portales del Río",
  "Porvenir",
  "Prado Norte",
  "Prados del Norte",
  "Primero de Mayo",
  "Principito",
  "Progresar",
  "Pueblo Nuevo",
  "Puerto Frazadas",
  "Quebradagrande",
  "Quintas de San Felipe",
  "Rafael Uribe Uribe",
  "Rojas",
  "Rubén Cruz Vélez",
  "Río Paila",
  "Sajonia",
  "Salesiano",
  "Samán del Norte",
  "San Antonio",
  "San Benito La Rivera",
  "San Carlos",
  "San Fernando Nuevo",
  "San Fernando Viejo",
  "San Isidro",
  "San Judas Tadeo",
  "San Lorenzo",
  "San Lucas",
  "San Luis",
  "San Martín",
  "San Pedro",
  "San Pedro Claver",
  "San Rafael",
  "San Vicente",
  "San Vicente de Paúl",
  "Santa Ana",
  "Santa Bárbara",
  "Santa Fe",
  "Santa Helena",
  "Santa Inés de Comfamiliar",
  "Santa Lucía",
  "Santa Mónica",
  "Santa Rita del Río",
  "Santa Rosa",
  "Santo Tomás",
  "Sucre",
  "Tenerife",
  "Tierradentro",
  "Villa del Sur",
  "Villa Liliana",
  "Villa Mercedes",
  "Villa Nelly",
  "Villa Sandra",
  "Villa Sofía",
  "Villapaz",
  "Villas de la Colina",
  "Villas de San Antonio"
];
