export const BARRIOS_TULUA = [
  "Alfonso López",
  "Altos de Santa Bárbara",
  "Antonio Nariño",
  "Brisas del Cauca",
  "Buenos Aires",
  "Centro",
  "Chicoral",
  "Ciudadela del Sur",
  "El Bosque",
  "El Jardín",
  "El Jazmín",
  "El Prado",
  "El Recreo",
  "El Vergel",
  "Gaitán",
  "Guayacanes",
  "La Campiña",
  "La Castellana",
  "La Estrella",
  "La Esperanza",
  "La Gran Vía",
  "La Isla",
  "La María",
  "Las Américas",
  "Las Brisas",
  "Las Colinas",
  "Las Ferias",
  "Los Alpes",
  "Los Arrayanes",
  "Los Cedros",
  "Los Cámbulos",
  "Los Naranjos",
  "Los Robles",
  "Maracaibo",
  "Miraflores",
  "Modelia",
  "Nariño",
  "Obrero",
  "Palermo",
  "Paraíso",
  "Paso del Comercio",
  "Pasoancho",
  "Prado Norte",
  "Progresar",
  "Pueblo Nuevo",
  "Rafael Uribe Uribe",
  "San Antonio",
  "San Fernando Nuevo",
  "San Fernando Viejo",
  "San Isidro",
  "San Judas Tadeo",
  "San Lucas",
  "San Martín",
  "San Pedro",
  "San Vicente",
  "Santa Ana",
  "Santa Bárbara",
  "Santa Fe",
  "Santa Helena",
  "Santa Mónica",
  "Santa Rosa",
  "Santo Tomás",
  "Sucre",
  "Tenerife",
  "Tierradentro",
  "Villa del Sur",
  "Villa Liliana",
  "Villa Mercedes",
  "Villa Nelly",
  "Villa Sandra",
  "Villa Sofía",
  "Villapaz",
  "Villas de la Colina",
  "Villas de San Antonio"
];
